// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Recommend/banner.vue')['default']
    BottomRecommend: typeof import('./src/components/Detail/BottomRecommend.vue')['default']
    ClassifyList: typeof import('./src/components/Classify/ClassifyList.vue')['default']
    Detailchapter: typeof import('./src/components/Detail/Detailchapter.vue')['default']
    Directory: typeof import('./src/components/Detail/Directory.vue')['default']
    Listitem: typeof import('./src/components/bangdan/listitem.vue')['default']
    Menu: typeof import('./src/components/Detail/Menu.vue')['default']
    Registered: typeof import('./src/components/User/registered.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanShareSheet: typeof import('vant/es')['ShareSheet']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
